### PR TITLE
update to 1.4.6

### PR DESCRIPTION
**Pull request by gillins**

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@ocefpaf I'm a bit surprised by this error: https://travis-ci.org/conda-forge/rios-feedstock/jobs/411602570#L607. Does this point to a problem with `libgdal` on OSX?

**Comment by gillins** [comment]
`gdalwarp` does seem to now pull in `ncurses` for some reason...

**Comment by ocefpaf** [comment]
A lot is coming from `defaults` on OS X including `ncurses` and `python` itself.
Not sure where to start rebuilding things there to make this work b/c I did rebuild `gdal` deps last week and Linux is fine. Looks like something specific to OS X.
@isuruf do you have any ideas?

**Comment by gillins** [comment]
Yes I can see that the packages chosen for [this OSX build](https://travis-ci.org/conda-forge/rios-feedstock/jobs/411602568) are from conda-forge, but when `libgdal` was [last rebuilt](https://circleci.com/gh/conda-forge/libgdal-feedstock/87?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) they were largely from defaults. I'll try and get a new `libgdal` build up and see what happens...

**Comment by ocefpaf** [comment]
>  I'll try and get a new `libgdal` build up and see what happens...

Thanks! I'm seeing this issue a lot with OS X. Probably need to stat re-building things in topological order for `libgdal` to solve that.

**Comment by ocefpaf** [comment]
@gillins that linter message is a bug, don't bother trying to fix it.

(We are working on it...)

**Comment by gillins** [comment]
@ocefpaf we still seem to have a broken `libgdal` on OSX - is there anything we can do about this in the short term - or do we just wait?

**Comment by ocefpaf** [comment]
I'm trying to re-build it but I'm stuck with the many libraries I had to re-build without the `.la` files :-(

See https://github.com/conda-forge/conda-forge.github.io/issues/621 for more info.

I'll "sprint" on this over the next few days. I'll keep you posted.

PS: I already did `hdf4`, `json-c`, and `libspatialite`. I'm stuck on `curl` at the moment:

https://travis-ci.org/conda-forge/curl-feedstock

**Comment by gillins** [comment]
> I'm trying to re-build it but I'm stuck with the many libraries I had to re-build without the .la files :-(

Wow - didn't see this was happening - a big job! BTW https://travis-ci.org/conda-forge/curl-feedstock/jobs/422261897#L4240 could be a Python 2/3 problem...

**Comment by gillins** [comment]
@ocefpaf this still seems to grabbing an old build of `libgdal` on OSX (https://travis-ci.org/conda-forge/rios-feedstock/jobs/425035228#L628). Any thoughts? No hurry to respond - I know you are incredibly busy...

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
