### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
Just testing...

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins I removed `defaults` from the builds and moved `libgdal 2.3.1` build number's `0` and `1` to broken. No idea what is going on Windows but at least OS X is now passing :smile:

**Comment by gillins** [comment]
Thanks @ocefpaf ! Is there a reason why you changed it to use `pip`? It seems to have a problem on win/py27....

**Comment by gillins** [comment]
See #15

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf ! Is there a reason why you changed it to use pip? It seems to have a problem on win/py27....

Sorry for not answering. (I was away for a long weekend here.)

As you probably already found out there was no strong reason to use `pip`. It is the recommended way to install but we can break that rule when it makes sense.

I just wonder why it was causing trouble there.

**Comment by gillins** [comment]
> It is the recommended way to install but we can break that rule when it makes sense.

Good to know. Thanks for all your help with this - `gdalwarp` etc seems all good on OSX with the latest `gdal`!

**Pull request closed without merging**
